# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        python-version: [ '3.6','3.7','3.8' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install . 
    - name: run pytests
      run: |
        pip install pytest pytest-ordering pytest-cov
        pytest -vvv
    - name: Generate coverage report
      run: |
        pytest --cov=./ --cov-report=xml:unit.coverage.xml
    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./unit.coverage.xml
        flags: unit
        env_vars: PYTHON
        name: codecov-unit
        fail_ci_if_error: false
